version: '3'
services:
    articlesdatabase:
        command: 'npm run dev'
        build:
            context: .
            dockerfile: Dockerfile
        image: articlesdatabase
        ports:
            - '3000:3000'
        networks:
            - sail
networks:
    sail:
        driver: bridge
